"""create educations table

Revision ID: f938bc45e647
Revises: 8fb0a61afc8c
Create Date: 2026-08-13 20:19:02.033662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f938bc45e647'
down_revision: Union[str, Sequence[str], None] = '8fb0a61afc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educations')
    # ### end Alembic commands ###
